var app = angular.module('app', [])

app.service('results', function($rootScope) {
    var results = {};
    return {
        set : function(newRes){
            results = newRes
            $rootScope.$broadcast("resultsChanged",results)
            console.log(results)
        },
        get : function(){
            return results
        }
    }
})

app.directive('phSliders', function() {
    return {
        restrict: "A",
        require: "^ngModel",
        scope: {
            ngModel: '='
        },
        template: ['<div class="dosingMenu">',
            '<div class="dosingMenuLeft">',
            '<div class="slider sliderMax blue"></div>',
            '</div>',
            '<div class="buttonArea">',
            '<span class="number">{{ngModel}}</span>',
            '<button class="btn btn-small btn-primary">Apply</button>',
            '</div>',
            '</div>'
        ].join("\n")

    }
});

var promptCtrl = function($scope,results) {
    $scope.patt = [{"val":""}];
    $scope.addPatt = function() {
        $scope.patt.push({"val":""})
    }
    $scope.clear = function() {
        $scope.patt = [{"val":""}]
    }
    $scope.search = function() {
        //Get JSON here
        var res = { "query":"AV[HELPARM]{1,6}HADDD","num":4,"rng":[0,2],"res":[{ "seq":"MHHVGERLRIEAHQQRERGEHGEHREFAAADVLQLRDVIVRHRAEIHALVHPQRVGGAENQRECRAERDPEIELDGGEDHHELADETRRARQAAIGHREQHRERGELRHHVDDAAVIGDLARVQAVVQHADAQEHRARHETVRDHLNDRAFDAQLVEDEEAERDEAHVRDRRIRDEFLHVRLHHRDEADVDHRDQRQRDHDGREEVARVRRDRQREAQETVRAELQHDRGQHDRAARRRFDVRVRQPRVHRPHRHLHREREEERDEEQHLRRHRDLRVLPRREVERMRLRVQIDQRDQHQQRAGERVQEELERRVHAVRAAPHADDDVHRDQRRLEEHVEQQAVSRREHADHDPRQDQERGEILRHVLGDHLPAGDHDDYRDERGQHDEPHRDAVDAQVIRDVETLDPRRLLDELQRGGARIEAGDQRDRHGQARQRADQRDPARRARMLVGTDREHDEAENDRQPDRGTENRKRVH" , "acc":"YP_332856.1" , "desc":"gi|76811319|ref|YP_332856.1| hypothetical protein BURPS1710b_1447 [Burkholderia pseudomallei 1710b]" , "org":"Burkholderia pseudomallei 1710b" , "db":"custom" },{ "seq":"MIRRQITWALLCMTLPSAAYPGPADHPAGHLPTHYLAAPGDDAWSGRLHALHFRPQPDMRETSRPPAIWEAAEKLDARPPDTRQLWTFQRGDAVARNAVPLRWEALAPAQQKLLDGRDGHGAIRLGYLRGVRRHEIDAPQLRRRASILGAVRGAHVQLLGPPGFTLDARHTDFRRRHAKRPWTVYIGANDGMLHAFDALTGSERFAVIPDAALPAVARNTAPGQPAPTPVCRRPFAADAWTGAQWRSVLACATGAMAPGLFLVDVTNPDADIPPPLLTYDTSDDPAVGHMADPIPIAPLADDSGVQSRWFAISGNGDGRPDMESRLLLLALDQPRAVPWQPGRTAFAITVPSSASRGGLGAPAVALGINGHATFAYAGDRHGQVWRFDLRGTPPWPQALGRNAVERQQPFFTATSRAGLRQRIVGPILLAATAGGPLLVFTAIDPAGATTLYGVRDVNHGQRKLAREHLAGRTTSETNDAVALHADDDRPIDAGWHIDLPTGHAPDDLVSAGQGSLLLITRDADGRSRAYLLDPRSGLPVDGKVRSGRVLASEPLITVHAAQPVTQADGSSTQVIQAQLWQAVGNRLQAMATDRQSRRLGRLNWREVLEEGIR" , "acc":"YP_003746470.1" , "desc":"gi|300704867|ref|YP_003746470.1| type IV pilus assembly protein, tip-associated adhesin pily [Ralstonia solanacearum CFBP2957]" , "org":"Ralstonia solanacearum CFBP2957" , "db":"custom" },{ "seq":"MLSASSLYAAIDLGSNSFHMLVVREVAGNIQTVARIKRKVRLAAGLDSENHLSDEAMERGWQCLRLFSEQLQDIPAEQIRVVATATLRLASNAGTFLQTAQHILGCPVNVISGEEEARLIYQGVAHTTGGSDKRLVVDIGGGSTELVTGSGSQTTSLFSLSMGCVTWLERYFGDRHLAKANFEQAELAARAMIRPIAAELREHGWQVCVGASGTVQALQEIMMAQGMDERITLSKLQQLKQRAIQCGKLEELEIEGLTLERALVFPSGLSILIAIFTELNIHSMTLAGGALREGLVYGMLHLPIDRDIRSRTLKNIQRRFTIDAEQADRVRNLAESFARQVSHSWKLDDRCRELLDSACLMHEIGLSVDFKQAPQHAAYLIRHLDLPGFTPAQKKLLATLLQNQVNSIDLAVLSQQNAIPPRMAERLCRLLRLAIIFSSRRRDDTLPAVRLHADDDALHVTLPAGWLEAHPLRAELLEQECHWQSYVHWPLTIG" , "acc":"YP_003739583.1" , "desc":"gi|300714780|ref|YP_003739583.1| guanosine-5'-triphosphate,3'-diphosphate pyrophosphatase [Erwinia billingiae Eb661]" , "org":"Erwinia billingiae Eb661" , "db":"custom" },{ "seq":"MTRRQTACALLCSALTSATHPGTADHPAGHLPTHYLAAPGDDAWSGRLHALHFRPPPNMRETSRPPAIWEAAEQLDARPPDTRQLWTFQQGDAIARNAVPLRWEALAPAQQKLLDGGGGHGTIRLGYLRGVRRHEIDAPQLRRRASILGAVRGAHVQLLGPPGFTLDVRHTDFRQRHAKRPWTVYIGANDGMLHAFDALTGSERFAVIPDAALPAVARNTAPGQPAPTPVCRRPFAADAWTGAQWRSVLACATGAMAPGLFLVDVTNPDAQTPPPLLAYDTRDDPAVGHMADPIPIAPLADDSGVQSRWFAISGNGNGPPNMESRLLLLALDQPRAVPWQPGRTAFAITVPSVASRGGLGAPAVALGTNGHVTFAYAGDCHGQVWRFDLRGTPPWPQALGRNAAERQQPLFTATSRAGLRQRIVGPILLAATAGGPLLVFTAIDPAGAATLYGVRDATHGQRKLAREHLAGRTASETNDAVALHADDDRPIDAGWRIDLPAGHAPDDLVSAGQDSLLLITHDADGRSRAYLLDPRSGLPVDGKLRSGRMLASEPLVTVHAAPPVTQADGSSTQVIQTQLWQAMGNRLQTMATDRQSRRLGRLNWREVLEEGMR" , "acc":"YP_006030476.1" , "desc":"gi|386334305|ref|YP_006030476.1| type 4 fimbrial biogenesis protein pily1-related protein [Ralstonia solanacearum Po82]" , "org":"Ralstonia solanacearum Po82" , "db":"custom" },{ "seq":"MAHTEHQTMRRVLRREIAGTIGLLTDEHDFTAMLRYRTFAFDDHATYLQQVEALLRTLAAQGGHTTVALFDPEEYAEFCAETGLEPDAPSSRTRFTAELAATGPTVPYEGQPLADLVPNLIDEAVRRATWQYATTVLTRIGSCASCGEDIGRAAFARASHLLARVLDTADPGHRHLVCSVSTTPEGVIAVLHADDDADGTARLDETEALEFTTVLALGIATRSAGGLVMRTSAPGRTDRVYGWRLRGEGLHPLTAGEVFDAYCTDIASGEIVSPESGVDYSEPPDLGDAEHPTGHTH" , "acc":"NP_828149.1" , "desc":"gi|29833515|ref|NP_828149.1| hypothetical protein SAV_6973 [Streptomyces avermitilis MA-4680]" , "org":"Streptomyces avermitilis MA-4680" , "db":"custom" },{ "seq":"MTAAALPPLDWRAMPLHGRVLIEASAGTGKTWNIGVIYLRLLLERGLRVEQILVTTFTDAAAQELRERLRRRLVEAERLLEAAARDAASVDPLESWLAALCPDADSVRLALRRIQLARSDLDRAPVSTIHALCQRIQRDYPLQSGAAFADDQLFDEQQLMRECVEDFWRRRYLTGAVDPREAELLLKDGPEGLLRDLGGLANSADARIEAGGLAELERQLDALCTDASIAELRRLAGDKSLYAPRKTALSNRLGKIADALQSNDEETLAARLDKTFEPDAVLEQEAPESTEPLNTHPLIKALQALRPLLGLRDVFTRGAVLADAAQACREEMPRRARQRHVLTFSMLIDAVYQRLCGEAADAVLADRLFDAFPVALIDEFQDTDQRQFAIFERIYRERGTLVMIGDPKQAIYSFRGGDIAAYLRAGAQAGQRFSLGTNHRSSRALVEALNAWYGHTEGGFGQLPIRYQPVAPAGKADGQPYTVDGQPVAQPLVFHPFHGDALDKKGKPLDALGDLEALALDDCANRIAELLNDPRQAIGGRPVTPGDVAVLLSTNNQVVALRQRLVARGVPCVGSGRGNIFAGEVARELELILYAVLHADDDQAVRGALATTLLGATLEQFHAWQAQPAAFERELERFEAWRALVRSRGVLALVGELLAARATALLALPEGERVLTDLRHLGELLAAEEGARQGLDGLYAWLQEMRREGGDGDAEAADERQLRIESDARRVQLLTIHASKGLEFPLVFLPLAWRIRSQGGSYAPKLLRYHDDAGQRCVDLGSAHFVEHCARHFREELEERLRLLYVALTRTVHAVHVYWVDRGPLPDGDAQTWEWAAIDLLLEQARQKLALPAGEASLDAMAAALGGMRLAAPFADTFTRYRPPAEAPAPRAAQAPLPALRPFQWLHSFSGLTRHAAAVLIDDSGSADETGAEEPVVEADEVVEDGRLLALHPLRGPRFGDAVHQVFELAQPGPLWPDQRQLLHRQLGAQAVAAPHLAHEEALERVGRMIDRARQADLGGGLRLLDLAPKQRIAEFEFQFPVRQVPLATLRRICAAHGHADAIPASLDATTLNGMLTGFADLIFAWDGRFHVLDYKTNWLGARLGDYRGEPLDAAMAAHHYPLQALLYTVALHRYLRQRMDGYTAERQLGESWYLFVRALGLAPGLGVWRRRWPAALVEALDDAFAGAQEAAA" , "acc":"YP_007589638.1" , "desc":"gi|469817554|ref|YP_007589638.1| ATP-dependent exonuclase V beta subunit, helicase and exonuclease domain-containing [Rhodanobacter sp. 2APBS1]" , "org":"Rhodanobacter sp. 2APBS1" , "db":"custom" },{ "seq":"MARTIPLERVRNIGIAAHIDAGKTTTTERILFYSGVVHKMGEVHEGTAVTDWMAQERERGITITAAAISTSWLDHRINIIDTPGHVDFTIEVERSMRVLDGVIAVFCSVGGVQPQSETVWRQAERYQVPRIAFINKMDRTGADFFKVYGQIRDRLRANAVPIQVPVGRESDFHGLVDIVAMKTYLYTNDLGTDIQISDEIPEEVQDLVAEYREKLLEAVAETDEALMEKYLEYLEGGDALTEEEVRHSLRQGTIKGLIVPVICGSSFKNRGVQRLLDAVVDYLPAPTEVPPIKGILPDGEEAVRHADDDVALSALAFKVMADPYGRLTFVRVYSGVLQKGSYIYNATKNKKERISRLIVLKSDERIEVEELRAGDLGAALGLKDTLTGDTICDEANPIILESLYIPEPVISVAVEPKTKQDMEKLSKALQSLSEEDPTFRVSIDSETNQTVIAGMGELHLEILVDRMLREFKVEANIGAPQVAYRETIRKSVRTEGKFIRQSGGKGQYGHVVIELEPGEPGSGFEFVSKVVGGSVPREYINPAEQGMKEACESGVIAGYPLIDVKATLVDGSYHDVDSSEMAFKIAGSMAIKNGVTKASPVLLEPMMKVEVEVPDDFIGNVIGDLNSRRGQIEGQETDQSQGIAKVVAKVPLATMFGYATDIRSKTQGRGVFSMEFSHYEEVPRSVAETIIAKSKGN" , "acc":"YP_005070131.1" , "desc":"gi|479130171|ref|YP_005070131.1| translation elongation factor EF-G [Arthrospira platensis NIES-39]" , "org":"Arthrospira platensis NIES-39" , "db":"custom" }] }
        results.set(res)
    }

}

var resCtrl = function($scope,results) {
    $scope.results = false;
    $scope.$on('resultsChanged',function(event,res){
        $scope.results = res
    })
    $scope.matchRng = function(seq,regex) {
        var patt = new RegExp(regex,"i");
        var match = patt.exec(seq);
        console.log(match)
        var start = match.index
        var text=match[0];
        var end = start+text.length;
        var out = start + " - " + text + " - " + end
        console.log(out)
        return out
    }

}
